name: Build Custom Windows
on:
  push:
    branches:
      - feature/search-and-oneclick
  workflow_dispatch:

jobs:
  build:
    name: Build Windows x64
    runs-on: windows-2022
    env:
      target-name: QtScrcpy
      vcvarsall-path: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
      vcinstall-path: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC'
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: 5.15.2
          target: desktop
          arch: win64_msvc2019_64
          dir: ${{ github.workspace }}/qt

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Build MSVC
        shell: cmd
        env:
          ENV_VCVARSALL: ${{ env.vcvarsall-path }}
          ENV_QT_PATH: ${{ github.workspace }}/qt/Qt/5.15.2
        run: |
          call python ci\generate-version.py
          call "ci\win\build_for_win.bat" RelWithDebInfo x64

      - name: Package
        env:
          ENV_VCVARSALL: ${{ env.vcvarsall-path }}
          ENV_VCINSTALL: ${{ env.vcinstall-path }}
          ENV_QT_PATH: ${{ github.workspace }}/qt/Qt/5.15.2
        run: |
          cmd.exe /c ci\win\publish_for_win.bat x64 ..\build\QtScrcpy-custom-win-x64
          Compress-Archive -Path ci\build\QtScrcpy-custom-win-x64 ci\build\QtScrcpy-custom-win-x64.zip

      - uses: actions/upload-artifact@v4
        with:
          name: QtScrcpy-custom-win-x64
          path: ci\build\QtScrcpy-custom-win-x64
