name: Build Custom Windows
on:
  push:
    branches:
      - feature/search-and-oneclick
  workflow_dispatch:

jobs:
  build:
    name: Build Windows x64
    runs-on: windows-2022
    env:
      vcvarsall-path: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
      vcinstall-path: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC'
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: 5.15.2
          target: desktop
          arch: win64_msvc2019_64

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set Version
        shell: bash
        run: echo "3.0.0" > QtScrcpy/appversion

      - name: Configure CMake
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_PREFIX_PATH="%QT_ROOT_DIR%\lib\cmake\Qt5" -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Visual Studio 17 2022" -A x64 ..

      - name: Build
        shell: cmd
        run: |
          cd build
          cmake --build . --config RelWithDebInfo -j8

      - name: Package
        shell: cmd
        env:
          ENV_VCVARSALL: ${{ env.vcvarsall-path }}
          ENV_VCINSTALL: ${{ env.vcinstall-path }}
          ENV_QT_PATH: ${{ env.QT_ROOT_DIR }}\..\..
        run: |
          set publish_dir=package\QtScrcpy-custom-win-x64
          mkdir %publish_dir%

          xcopy output\x64\RelWithDebInfo\* %publish_dir%\ /E /Y
          xcopy QtScrcpy\QtScrcpyCore\src\third_party\adb\win\* %publish_dir%\ /Y
          xcopy QtScrcpy\QtScrcpyCore\src\third_party\scrcpy-server %publish_dir%\ /Y
          xcopy keymap %publish_dir%\keymap\ /E /Y
          xcopy config %publish_dir%\config\ /E /Y

          call "%ENV_VCVARSALL%" x64
          "%QT_ROOT_DIR%\bin\windeployqt.exe" %publish_dir%\QtScrcpy.exe

          if exist %publish_dir%\iconengines rmdir /s/q %publish_dir%\iconengines
          if exist %publish_dir%\translations rmdir /s/q %publish_dir%\translations

      - uses: actions/upload-artifact@v4
        with:
          name: QtScrcpy-custom-win-x64
          path: package\QtScrcpy-custom-win-x64
